import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import SideNav from "@/components/common/nav/SideNav";
// 전역 Css
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "supa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SideNav/>
        {children}
      </body>
    </html>
  );
}
